/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IContractTeacher,
  IContractTeacherInterface,
} from "../IContractTeacher";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getCourseName",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tockenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IContractTeacher__factory {
  static readonly abi = _abi;
  static createInterface(): IContractTeacherInterface {
    return new utils.Interface(_abi) as IContractTeacherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IContractTeacher {
    return new Contract(address, _abi, signerOrProvider) as IContractTeacher;
  }
}
